apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace : default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
        - name: dotnet-app
          image: danielshloklabs/dotnetbuild:1.1.<BUILD_ID>
          ports:
            - containerPort: 80


apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-service
  namespace : default
spec:
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 
  type: NodePort
